export   const postagem = [
    {autor: "Wandinha",
    fotoDePerfil: "./assets/Wednesday.jpg",
    foto: "./assets/QuartaFeira.jpg",
    quemCurtiu: "Mãozinha",
    quemCurtiuFoto: "./assets/Mãozinha.jpg",
    quantosCurtiram: "outras 1.349.507 pessoas",
    descricao: "Eles nem derramaram sangue de porco de verdade",
    quantosComentarios: "Ver todos os 17.340 comentários",
    quemComentou: "Enid",
    comentario: "Você PROVOU?!?!?!?!?!?"},

    {autor: "Enid",
    fotoDePerfil: "./assets/Enid.jpg",
    foto: "./assets/Wenid.jpg",
    quemCurtiu: "Morticia",
    quemCurtiuFoto: "./assets/Morticia.jpg",
    quantosCurtiram: "outras 1.274.516 pessoas",
    descricao: "Dos mesmos criadores de 'Eu sou alérgica a cores' 🏳️‍🌈",
    quantosComentarios: "Ver todos os 179.804 comentários",
    quemComentou: "Wandinha",
    comentario: "Eu vou te dar 13 segundos para apagar isso."},

    {autor: "Morticia",
    fotoDePerfil: "./assets/Morticia.jpg",
    foto: "./assets/Morticia-e-Wandinha.jpg",
    quemCurtiu: "Gomez",
    quemCurtiuFoto: "./assets/Gomez.jpg",
    quantosCurtiram: "outras 13.315 pessoas",
    descricao: "Eu sempre estarei aqui para você 🖤",
    quantosComentarios: "Ver todos os 9.804 comentários",
    quemComentou: "Enid",
    comentario: "Nossa, vcs duas são igualzinhas..."}
  ]